services:
  api:
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_PATH: /data/caen.db
    volumes:
      - ./data:/data
      - ./data/caen.db:/app/caen.db
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

