services:
  api:
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_PATH: /data/caen.db
    volumes:
      - ./data:/data
    restart: unless-stopped

